Traffic Portal tests: Remove interactive browser.debugger() lines (#4854)
* Remove interactive browser.debugger() lines
Fixes TypeError: browser.debugger is not a function

* Use protractor major version 7 to run the TP tests

(cherry picked from commit ff50ddbae4011c40cbbaaf82b272faa6807bf009)